name: py3.10-timemixer-smac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gxx_linux-64=14.1.0
  - gcc_linux-64=14.1.0
  - swig=4.2.1
  - pip=24.2
  - pip:
    - numpy==1.26.4
    - pandas==2.2.2
    - scipy==1.14.1
    - matplotlib==3.9.2
    - seaborn==0.13.2
    - scikit-learn==1.5.1
    - torch==2.4.0
    - smac==2.2.0
    - sktime==0.32.1
    - dask==2024.8.1
